### ISSUE TITLE
ValueError: Error when checking input: expected input_1 to have shape 

### ISSUE THREAD

**Issue by ShibaPrasad** [voxelmorph/voxelmorph#104]
Hi All,

I tried to use my own data set and used the below script:

test_miccai2018.py 0 /user/iibi/skuanar/Downloads/voxelmorph/models/miccai2018_10_02_init1.h5 10

**_I got the below error_**

ValueError: Error when checking input: expected input_1 to have shape (160, 192, 224, 1) but got array with shape (512, 512, 647, 1)

How to solve this mismatch problem.
*********************************************************************************************************************************

Traceback (most recent call last):
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 109, in <module>
    test(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 87, in test
    pred = diff_net.predict([X_vol, atlas_vol])
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1441, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (160, 192, 224, 1) but got array with shape (512, 512, 647, 1)

Process finished with exit code 1

**Comment by adalca** [comment]
you should change the size of the model (in test_miccai2018 it's passed in as (160, 192, 224) to your own size). However, now that your size of 647 won't work -- the model currently requires the data to be a multiple of 16. Also, it's likely that you should fine-tune (train) the model to your own data.
