### ISSUE TITLE
(#104) ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 64, 64, 82, 32), (None, 64, 64, 81, 32)]

### ISSUE THREAD

**Issue by ShibaPrasad** [voxelmorph/voxelmorph#105]
HI,
I am able to change the size of image to 512 by 512 by 512 and getting below error:

Traceback (most recent call last):
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 109, in <module>
    test(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/user/iibi/skuanar/Downloads/voxelmorph/src/test_miccai2018.py", line 63, in test
    net = networks.miccai2018_net(vol_size, nf_enc, nf_dec, use_miccai_int=False, indexing='ij')  
  File "/nfs/s-iibi54/users/skuanar/Downloads/voxelmorph/src/networks.py", line 146, in miccai2018_net
    unet_model = unet_core(vol_size, enc_nf, dec_nf, full_size=False)
  File "/nfs/s-iibi54/users/skuanar/Downloads/voxelmorph/src/networks.py", line 65, in unet_core
    x = concatenate([x, x_enc[-2]])
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/layers/merge.py", line 649, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/user/iibi/skuanar/anaconda3/lib/python3.7/site-packages/keras/layers/merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 64, 64, 82, 32), (None, 64, 64, 81, 32)]

**Comment by adalca** [comment]
I believe there is an error in your sizes. Can you please verify that `vol_size` is `[512, 512, 512]`? Perhaps print right before line 63?
