### ISSUE TITLE
Unable to load any of the provided models (voxelmorph-redesign)

### ISSUE THREAD

**Issue by sravan953** [voxelmorph/voxelmorph#172]
**Task** (what are you trying to do/register?)
Register a BraTS 2018 subject to the provided `atlas_norm.nii.gz`.

[please describe task here]

**What have you tried**
Running `register.py`:
- fixed - the provided `atlas_norm.nii.gz`.
- moving - random BraTS 2018 subject
- model - provided `cvpr2018_vm1_cc.h5`

... on Tensorflow 1.14.

**Error**
```
Traceback (most recent call last):
  File ".../voxelmorph-redesign/scripts/tensorflow/register.py", line 103, in <module>
    warp_predictor = vxm.networks.VxmDense.load(args.model).get_predictor_model()
  File "...\voxelmorph-redesign\voxelmorph\tensorflow_backend\model_io.py", line 95, in load
    model = cls(**config)
  File "...\voxelmorph-redesign\voxelmorph\tensorflow_backend\model_io.py", line 22, in wrapper
    retval = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'output_layers'
```

**Comment by adalca** [comment]
@sravan953  did you happen to try any of the other models?

@ahoopes should these models be working with the redesign, or will we provide new models?

**Comment by ahoopes** [comment]
We will be providing new modes for the redesign branch. The current models are probably not loadable since the default net architecture has changed a bit

**Comment by xiaocainiao-afk** [comment]
I got the same error
