### ISSUE TITLE
Train_img_template.py AssertionError: input_nodes (2) and input_layers (0) have to match

### ISSUE THREAD

**Issue by teen1992** [voxelmorph/voxelmorph#209]
Hello,

When I was trying to create an atlas with my own data by using train_img_template.py, I came across the following error:

Traceback (most recent call last):
  File "train_img_template.py", line 253, in <module>
    train(**vars(args))
  File "train_img_template.py", line 130, in train
    smooth_pen_layer=smooth_pen_layer)
  File "E:\RT work\AISegmentation\Code\voxelmorph-master\src\networks.py", line 546, in img_atlas_diff_model
    sm = nrn_utils.stack_models([pw, mn], [[0]])
  File "../ext/neuron\neuron\utils.py", line 796, in stack_models
    output_tensors = mod_submodel(models[mi], new_input_nodes=new_input_nodes)
  File "../ext/neuron\neuron\utils.py", line 942, in mod_submodel
    assert len(input_nodes) == len(input_layers), 'input_nodes (%d) and input_layers (%d) have to match' % (len(input_nodes), len(input_layers))
AssertionError: input_nodes (2) and input_layers (0) have to match

I only gave the data_dir argument which points to the directory of my own data, and the other parameters were their default values. Can anyone tell me where the problem could be? Thanks a lot!

**Comment by teen1992** [comment]
This problem was caused by the mixing use of keras and tf.keras. I solved the problem by:
1. replace layers.py, models.py and utils.py with those downloaded from https://github.com/adalca/neuron
2. change all the import keras into import tensorflow.keras
I used tensorflow 1.14.
