### ISSUE TITLE
Sizes of tensors must match except in dimension 4.

### ISSUE THREAD

**Issue by SangWoonJeong** [voxelmorph/voxelmorph#292]
Hello, i can check atlas data. that using no error.
so i used my CT prostate data.
but proceed error.

my data 
512 x 512 x 141 size.
and no change encoder, decoder size.
        encoder: [16, 32, 32, 32]
        decoder: [32, 32, 32, 32, 32, 16, 16]

I think, encoder and decoder size error.

How can i change this point?

**Task** (what are you trying to do/register?)

pytorch / train

y_pred = model(*inputs)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/woon/anaconda3/envs/DVF_augmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/woon/anaconda3/envs/DVF_augmentation/lib/python3.6/site-packages/voxelmorph/torch/networks.py", line 181, in forward
    x = self.unet_model(x)
  File "/home/woon/anaconda3/envs/DVF_augmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/woon/anaconda3/envs/DVF_augmentation/lib/python3.6/site-packages/voxelmorph/torch/networks.py", line 89, in forward
    x = torch.cat([x, x_enc.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 4. Got 71 and 72 (The offending index is 0)

so Input image shape checking. but same 1, 1, 512, 512, 141 size

Thanks

**Comment by adalca** [comment]
@SangWoonJeong I think the problem is the same as in https://github.com/voxelmorph/voxelmorph/issues/48
Basically because the current implementation uses a UNet first 4 levels, your data has to be a multiple of 2^5 = 32. I would pad your last dimension by [9, 10]. to make it 160 (=5*32).

**Comment by SangWoonJeong** [comment]
Oh thanks. i clear this program.
but my data size is so big. (512, 512, 144)
My gpu 11GB X 2(2080TI 2#)
command : Pytorch : out of memory.

Any this problem solution ? (Patch size ???)

**Comment by adalca** [comment]
You can certainly try braking it up in patches during training. You can probably try to apply it at inference time to the whole volume.

An alternative is to operate at half resolution, and at inference upsample the deformation field.

**Comment by SangWoonJeong** [comment]
Yes, sir.
I used image resize and cut 256 256 64.
Add question,
Using register.py, 
predict
moved, wrap = model(input_moving, input_fix, registration = True)
So I can using wrap(DVF) data.
spatial translation using label data.
ex.
moved_label = ?????(input_moving_label, **wrap**)

How can i moved label image, using moved wrap data ??
thanks so much.

**Comment by adalca** [comment]
you're probably looking for [`model.apply_transform()` ](https://github.com/voxelmorph/voxelmorph/blob/3e37cf9467c32c2969432c2e9fad8509fcfb48c8/voxelmorph/tf/networks.py#L207), although you probably want to use "nearest" interpolation

**Comment by SangWoonJeong** [comment]
I was using it as pytorch, but I think I need to change it to tf.
Thank you for the quick and kind answer.
I'm sorry, but I'll ask if you have any other problems with tf.
Thank you.
