### ISSUE TITLE
ValueError when trianing voxelmorph on my own 2 d dataset

### ISSUE THREAD

**Issue by 1299246210** [voxelmorph/voxelmorph#315]
**Task** (what are you trying to do/register?)

Hi, I want to use vxm to train a model to register 2-D photos of high-speed railway Chassis images(gray),Resolution is 20688x1120. my tf is 2.3.0  ,Use the branch: master. Since I'm new to this,I don't know how to slove it. Thanks a lot.

**What have you tried**

I converted the JPG file to NPZ, and use them to train a model .
 Using the command :  python train.py  C:\Users\12992\vox1\input  --model-dir  C:\Users\12992\vox1\output

**Details of experiments**

I get errors:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for '{{node unet_enc_pooling_0/MaxPool3D}} = MaxPool3D[T=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 2, 1]](unet_enc_conv_0_0_activation/LeakyRelu)' with input shapes: [?,1,1120,20688,16].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 96, in <module>
    model = vxm.networks.VxmDense(
  File "C:\ProgramData\Anaconda3\lib\site-packages\voxelmorph\tf\modelio.py", line 22, in wrapper
    retval = func(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\voxelmorph\tf\networks.py", line 87, in __init__
    unet_model = Unet(
  File "C:\ProgramData\Anaconda3\lib\site-packages\voxelmorph\tf\networks.py", line 825, in __init__
    last = MaxPooling(max_pool[level], name='unet_enc_pooling_%d' % level)(last)
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\layers\pooling.py", line 566, in call
    outputs = self.pool_function(
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\nn_ops.py", line 4642, in max_pool3d
    return gen_nn_ops.max_pool3d(
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 5372, in max_pool3d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\func_graph.py", line 591, in _create_op_internal
    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\ops.py", line 1974, in __init__
    self._c_op = _create_c_op(self._graph, node_def, inputs,
  File "C:\Users\12992\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\ops.py", line 1815, in _create_c_op
    raise ValueError(str(e))

ValueError: Negative dimension size caused by subtracting 2 from 1 for '{{node unet_enc_pooling_0/MaxPool3D}} = MaxPool3D[T=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 2, 1]](unet_enc_conv_0_0_activation/LeakyRelu)' with input shapes: [?,1,1120,20688,16].

**Comment by adalca** [comment]
@1299246210 ,

It seems that when the data is loaded it's loaded in as a 3D volume instead of 2D. 
Can you please check the size in the npz file and how it looks like when loaded from the generator?

**Comment by 1299246210** [comment]
@adalca ，Thanks ，I will try to examine them.

**Comment by 1299246210** [comment]
> It seems that when the data is loaded it's loaded in as a 3D volume instead of 2D.
> Can you please check the size in the npz file and how it looks like when loaded from the generator?

Hi，the vol size of the npz file is (2,1120,10688),(I only have two images now).my in shape parameter in networks.py is (1120,10688),Is there a mistake here?

**Comment by adalca** [comment]
if it's 2D, seems to me like each image should be `[1120, 10688]`, no?

**Comment by 1299246210** [comment]
@adalca ,Yes, The two images that I have right now are at the same resolution ,which is [1120, 10688]. Does VXM have a limit on image size?

**Comment by adalca** [comment]
No, it does not have an (upper) limit of image size

The problem is you are feeding in volumes that are `(2,1120,10688)`, they need to be ` (1120,10688)`

You can see this from the error: 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for '{{node unet_enc_pooling_0/MaxPool3D}} = MaxPool3DT=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 2, 1]' with input shapes: [?,1,1120,20688,16].
```
The input shape that the model is getting from you is `[?,1,1120,20688,16]`, which means the volume dimensions are `[1,1120,20688]`. This first `1` is extra.

**Comment by 1299246210** [comment]
Thank you for your patient answer！，I made the dataset (A npz file,which has one npy file in it, with two images  ,so the vol size is 2x1120x10688) following the instructions of the tutorial, I really don't know how to make it work. Could you tell me how to solve this problem?

**Comment by adalca** [comment]
Separate the volumes into two volume files: scan1.npz, and scan2.npz (or whatever you think the naming should be), each with a single volume of size `(1120, 10688)`. 

When you say that you are following the instructions of the tutorial, can you point us to where you saw this?
We would like to clarify the instructions.

**Comment by 1299246210** [comment]
1.So, I separate them into two volume files: 1.npz, and 2.npz.
 And run `python train.py C:\Users\12992\vox1\input --model-dir C:\Users\12992\vox1\output`  
Then I get the same error as before:
`ValueError: Negative dimension size caused by subtracting 2 from 1 for '{{node unet_enc_pooling_0/MaxPool3D}} = MaxPool3D[T=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 2, 1]](unet_enc_conv_0_0_activation/LeakyRelu)' with input shapes: [?,1,1120,20688,16].`
It looks so weird.


2.In the **Registration of Brain MRI** part of the tutorial, 
`npz = np.load('tutorial_data.npz')
x_train = npz['train']
x_val = npz['validate']
 **#the 208 volumes are of size 160x192**
vol_shape = x_train.shape[1:]
print('train shape:', x_train.shape)`
I think of it as there are 208 images whit the size of 160x192 in one npz.
 Did I get it wrong?

**Comment by adalca** [comment]
1. What is the size of the volume in 1.npz? It has to be `[1120, 20688]`, I suspect you have it as `[1, 1120, 20688]`?

2. Ah, I see. The x_train there was loaded locally to be played with, it's not fed to a `train.py` file. If you want to use the train.py file you need npz files that have a single volume in them.

**Comment by 1299246210** [comment]
1. Yes, you are right! I'm sorry to have bothered you so long . It looks like I'm not converting the file the right way,I'm new to this. Could you tell me how to convert it correctly? Any software or code would be very helpful!
2. Oh, sorry,I misunderstood this. Thanks again for your patient answer!

**Comment by adalca** [comment]
How are you doing now? It's just a matter of extracting the zeroth entry in the first dimension before you save

**Comment by 1299246210** [comment]
Yeah,I successfully completed the correct conversion. 

But I ran into another problem when ran `python train.py C:\Users\12992\vox1\input --model-dir C:\Users\12992\vox1\output`.

`Epoch 1/1500
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    verbose=1
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1861, in fit_generator
    initial_epoch=initial_epoch)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:
    /data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /data2/anaconda3/vox/lib/python3.7/site-packages/voxelmorph/tf/losses.py:77 loss  *
        return 1.0 / (self.image_sigma**2) * K.mean(K.square(y_true - y_pred))
    /data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:1180 binary_op_wrapper
        raise e
    /data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:1164 binary_op_wrapper
        return func(x, y, name=name)
    /data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:561 subtract
        return gen_math_ops.sub(x, y, name)
    /data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py:10317 sub
        "Sub", x=x, y=y, name=name)
    /data2/anaconda3/vox/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:558 _apply_op_helper
        inferred_from[input_arg.type_attr]))

`TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type uint8 of argument 'x'.`

And I check the  data type of array elements in the npz file  ,they are all unit8.
How should I correct it? Thanks a lot!

**Comment by adalca** [comment]
Unfortunatey these frameworks like tf will by default want to work with float32. I recommend you change the format, e.g. by doing
```
data = data.astype('float')
data = data.max()
```
before saving

@ahoopes do we do any int-to-float transform in load_vol? should we?

**Comment by 1299246210** [comment]
Ok，I will try it later.Thanks again!
