### ISSUE TITLE
Model output error when using train_synthmorph.py 

### ISSUE THREAD

**Issue by bensarthou** [voxelmorph/voxelmorph#347]
Hi, 

**Task: Train SynthMorph model on a set of label using train_synthmorph.py** 

I want to train the SynthMorph model on a set of generated labels, using the example script provided in scripts/tf. 

**What have you tried**

I'm using the dev branch, uptodate at 16/09/2021 (d7d13fa756fd6fbe22b1f60a13b65df37b952784), with tensorflow/keras 2.6.0
Voxelmorph was installed via setup.py, as well as neurite and pystrum

I generated the labels (with my own code) using the "shape" method described in the SynthMorph paper and stored them in a folder with the glob pattern below (in .nii.gz file, with 26 labels; of size 160x160x192)

When I launch the command `python scripts\tf\train_synthmorph.py --label-dir e:\data\SynthShapes\*\*_origin_label_map.nii.gz --model-dir e:\data\models_SM_shapes_210916\ --out-labels e:\data\models_vxm\labels_shapes.npz`, it seems that it correctly load the data (it carries on without issues after the labels_to_image l157) but when the training starts (calling model.fit l196); it stops with the following error: 

```ValueError: ('Error when checking model target: expected no data, but got:', [array([[[[[0., 0., 0.],...```

**Details**
I found that tensorflow issued warnings when compiling the model: 

```WARNING:tensorflow:Output vxm_dense_transformer missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to vxm_dense_transformer.
WARNING:tensorflow:Output vxm_dense_flow missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to vxm_dense_flow.
```
Which would be coherent with the above error, as it seems vxm_dense_flow is never given to a loss (according to the error, not the code), whereas the grad Loss requires it.

I tried to dig into the VxmDense class to see from where the error could come from but I wasn't able to find the culprit
Maybe I am using wrongly the train_synthmorph script ?

Thanks in advance for your help,

**Comment by mu40** [comment]
I'm unable to reproduce the issue with d7d13fa756fd6fbe22b1f60a13b65df37b952784 and TensorFlow 2.6.0 from pip. How did you adapt the training script to read .npz files? The script in the dev branch only knows about .npy and .pickle. As a quick test, you could try `--out-labels ""`, which will optimize the overlap of all labels present in your training data.

**Comment by bensarthou** [comment]
Hi, 
Thank you for your quick answer. 
I did not modify any of the script as far as I know, I've re-installed everything, tried again and obtain the same issue this weekend. 
```
> C:\Users\BSU3\Documents\src\voxelmorph (dev -> origin)
λ pip freeze | grep -e keras -e tensorflow
keras==2.6.0
tensorflow==2.6.0
tensorflow-estimator==2.6.0

> C:\Users\BSU3\Documents\src\voxelmorph (dev -> origin)
λ git rev-parse HEAD
d7d13fa756fd6fbe22b1f60a13b65df37b952784

> C:\Users\BSU3\Documents\src\voxelmorph (dev -> origin)
λ pip uninstall voxelmorph
Found existing installation: voxelmorph 0.1
Uninstalling voxelmorph-0.1:
  Would remove:
    c:\users\bsu3\appdata\local\programs\python\python39\lib\site-packages\voxelmorph-0.1-py3.9.egg
Proceed (Y/n)? Y
  Successfully uninstalled voxelmorph-0.1

C:\Users\BSU3\Documents\src\voxelmorph (dev -> origin)
λ rm -rf build\

C:\Users\BSU3\Documents\src\voxelmorph (dev -> origin)
λ python setup.py install
[...]
Using c:\users\bsu3\appdata\local\programs\python\python39\lib\site-packages
Finished processing dependencies for voxelmorph==0.1

```
As for the --out-labels, I've tried the "" option, which has given the same result
Indeed, I was using a .npz file, but it seems to me that the code just switch to the "" option (else l120 in train_syntmorph.py file) in this case. 
I've also retry with a .npy file, but with no change in the error


I've also tried reverting to a previous commit, and I've managed to make the training work with the  `b616bb2 Update references. (#323)` commit. However, I'm unable to test the models generated with the test file, as it gives me another error: 

```
python scripts\tf\test.py --model e:\data\models_SM_shapes_210916\0990.h5 --pairs e:\data\SynthShapes\test_file_list_full.txt
2021-09-20 09:37:59.294533: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-09-20 09:37:59.338553: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: HP051DSY
2021-09-20 09:37:59.339033: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: HP051DSY
2021-09-20 09:37:59.339767: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\BSU3\Documents\src\voxelmorph\scripts\tf\test.py", line 81, in <module>
    registration_model = vxm.networks.VxmDense.load(args.model).get_registration_model()
  File "C:\Users\BSU3\AppData\Local\Programs\Python\Python39\lib\site-packages\neurite\tf\modelio.py", line 96, in load
    model = cls(**config)
  File "C:\Users\BSU3\AppData\Local\Programs\Python\Python39\lib\site-packages\neurite\tf\modelio.py", line 22, in wrapper
    retval = func(self, *args, **kwargs)
  File "C:\Users\BSU3\AppData\Local\Programs\Python\Python39\lib\site-packages\voxelmorph-0.1-py3.9.egg\voxelmorph\tf\networks.py", line 111, in __init__
AttributeError: 'dict' object has no attribute 'outputs'
```

**Comment by bensarthou** [comment]
Hi again, 

I've seen that you pushed a new commit this weekend (3d004df) that solved the issue with the training script 
Everything works correctly for me now, train_synthmorph.py and test.py,
Thank you a lot for your help !

**Comment by mu40** [comment]
You are right about the `--out-labels` option. I'm glad it works now!

________________________________________

**Comment by mu40** [comment]
>Hi again,
>
>I've seen that you pushed a new commit this weekend (3d004df) that solved the issue with the training script
>Everything works correctly for me now, train_synthmorph.py and test.py,
>Thank you a lot for your help !

You are right about the `--out-labels` option. I'm glad it works now!

**Comment by bensarthou** [comment]
Hi, 

Sorry for the previous message, I was celebrating a bit early it seems :/ 
As I was saying, your commit from this weekend (3d004df) solved the issue with the train.py script ! It was an issue with tensorflow v1 compatibility ? 

But I've tested now test.py with a model generated by the train.py (early iteration but I wanted to be sure it worked) and it failed with the aforementioned error: 

```C:\Users\BSU3\Documents\src\voxelmorph (dev -> origin)
λ git rev-parse HEAD
3d004df461caed23182365b99e315f2590df9d15

C:\Users\BSU3\Documents\src\voxelmorph (dev -> origin)
λ python scripts\tf\test.py --model e:\data\models_SM_shapes_210920\0010.h5 --pairs e:\data\SynthShapes\test_file_list_full.txt
2021-09-20 14:24:01.333308: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-09-20 14:24:01.361396: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: HP051DSY
2021-09-20 14:24:01.362183: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: HP051DSY
2021-09-20 14:24:01.362888: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\BSU3\Documents\src\voxelmorph\scripts\tf\test.py", line 81, in <module>
    registration_model = vxm.networks.VxmDense.load(args.model).get_registration_model()
  File "C:\Users\BSU3\AppData\Local\Programs\Python\Python39\lib\site-packages\neurite\tf\modelio.py", line 96, in load
    model = cls(**config)
  File "C:\Users\BSU3\AppData\Local\Programs\Python\Python39\lib\site-packages\neurite\tf\modelio.py", line 22, in wrapper
    retval = func(self, *args, **kwargs)
  File "C:\Users\BSU3\AppData\Local\Programs\Python\Python39\lib\site-packages\voxelmorph-0.1-py3.9.egg\voxelmorph\tf\networks.py", line 111, in __init__
AttributeError: 'dict' object has no attribute 'outputs'
```

I'm sorry to have claimed it worked a bit too early... Do you have any idea what could cause this error ? It seems like a incompatibilty of model between the one saved by train, and the one loaded by test

**Comment by mu40** [comment]
This is a separate issue, that we fixed a while ago for `register.py` by overriding the saved input model with `input_model=None` (but overlooked in `test.py`). PR #353 should resolve this now.

**Comment by adalca** [comment]
Thanks @mu40 !
