### ISSUE TITLE
Error when trying to use Mutual Information loss function

### ISSUE THREAD

**Issue by srivathsapv** [voxelmorph/voxelmorph#356]
I am trying to train a 3D affine registration network based on Voxelmorph idea and I'm trying to use mutual information as the loss function. I am getting the following error when trying to use the function provided in the `losses.py` file.

```
Traceback (most recent call last):
  File "./scripts/tf/train.py", line 272, in <module>
    loss=loss_fn, loss_weights=loss_weights
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/keras/engine/training.py", line 229, in compile
    self.total_loss = self._prepare_total_loss(masks)
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/keras/engine/training.py", line 692, in _prepare_total_loss
    y_true, y_pred, sample_weight=sample_weight)
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/keras/losses.py", line 71, in __call__
    losses = self.call(y_true, y_pred)
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/keras/losses.py", line 132, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
  File "/home/srivathsa/projects/voxelmorph/voxelmorph/tf/losses.py", line 332, in loss
    return -self.volumes(y_true, y_pred)
  File "/mnt/datasets/srivathsa/projects/neurite/neurite/tf/metrics.py", line 137, in volumes
    tf.debugging.assert_equal(tensor_channels_x, 1, msg)
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/tensorflow/python/ops/check_ops.py", line 557, in assert_equal
    return control_flow_ops.Assert(condition, data, summarize=summarize)
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/tensorflow/python/util/tf_should_use.py", line 193, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 163, in Assert
    return gen_logging_ops._assert(condition, data, summarize, name="Assert")
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 74, in _assert
    name=name)
  File "/home/srivathsa/miniconda3/envs/voxelmorph/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 442, in _apply_op_helper
    (input_name, op_type_name, values))
TypeError: Expected list for 'data' argument to 'Assert' Op, not volume_mi requires two single-channel volumes. See channelwise()..
```
I tried using `-self.channelwise` instead of `-self.volumes` in the `vxm.tf.losses.MutualInformation` class, but still getting the same error. @adalca or someone else, could you please help me out with this issue? Thanks.

**Comment by adalca** [comment]
interesting, could you tell us what tf version you are using? Also, can you comment out the tf assert in metrics.py and see if that makes this go away?

**Comment by srivathsapv** [comment]
Tensorflow version 1.14.0 and Keras version 2.3.0
Commenting out the assert statements [here](https://github.com/adalca/neurite/blob/dev/neurite/tf/metrics.py#L138) and [here](https://github.com/adalca/neurite/blob/dev/neurite/tf/metrics.py#L203) in the `neurite.metrics.MutualInformation` does make the error go away. But I was wondering if there is a cleaner way to do this. Thanks

**Comment by adalca** [comment]
Unfortunately we haven't used tensorflow 1.14 in a long time. Any chance you could try this with an environment with tf 2.4+ ?

**Comment by srivathsapv** [comment]
Sure will give it a try.
