### ISSUE TITLE
Value error non-matching shapes in 'Concatenate' layer when training model with 2-D images

### ISSUE THREAD

**Issue by zplasty** [voxelmorph/voxelmorph#382]
**Task** (what are you trying to do/register?)

Hello, I am trying to use voxelmorph to train a model to register 2-D photos of faces to build conditional templates based on age and other attributes. The photographs have resolution of 600x600. I am having issues though with errors when training my model. I am not sure why non-matching shapes are occuring as the original inputs all match in shape. Any help is appreciated.

**What have you tried**

I converted tif files to npz with volumes of size (600,600). I try to train the model by running the command:

python scripts\tf\train.py --img-list images\list.txt --model-dir models\output --gpu 0

**Details of experiments**

I get the following errors after this command:
Traceback (most recent call last):
  File "C:\Users\Sample_Image_Registration\PhotoRegistration\voxelmorph\voxelmorph\scripts\tf\train.py", line 140, in <module>
    model = vxm.networks.VxmDense(
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\neurite\tf\modelio.py", line 22, in wrapper
    retval = func(self, *args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\voxelmorph\tf\networks.py", line 135, in __init__
    unet_model = Unet(
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\voxelmorph\tf\networks.py", line 1116, in __init__
    last = _upsample_block(last, enc_layers.pop(), factor=max_pool[real_level],
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\voxelmorph\tf\networks.py", line 1235, in _upsample_block
    return KL.concatenate([upsampled, connection], name=name)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\merge.py", line 965, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer_v1.py", line 745, in __call__
    self._maybe_build(inputs)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer_v1.py", line 2072, in _maybe_build
    self.build(input_shapes)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\tf_utils.py", line 296, in wrapper
    output_shape = fn(instance, input_shape)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\merge.py", line 525, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 74, 74, 32), (None, 75, 75, 32)]

**Comment by randomAowu** [comment]
Hi, I'm having the same issues now. Have you solved this? Thanks for any help!

**Comment by adalca** [comment]
the voxelmorph core architecture (which you can change with your favorite thing) is a simple unet with 4 layers, which requires your input data to be a multiple of 32. This is likely the issue, unfortunately.
