### ISSUE TITLE
Cannot load pre-trained weight `.h5` of VoxelMorph using PyTorch

### ISSUE THREAD

**Issue by Chrisa142857** [voxelmorph/voxelmorph#452]
**Task** (what are you trying to do/register?)

Register using the pre-trained VoxelMorph Unet. Always Failed when loading `.h5`.

**What have you tried**

Code is simple:
```
import torch
m = torch.load("vxm_dense_brain_T1_3D_mse.h5") 
```
Output:
```
Traceback (most recent call last):
  File "NLST/val_NLST.py", line 49, in <module>
    evaluate_L2R(args, config_path, out_path)
  File "NLST/val_NLST.py", line 30, in evaluate_L2R
    reg(args)
  File "/content/NLST/register.py", line 66, in main
    model = vxm.networks.VxmDense.load(args.model, device)
  File "/usr/local/lib/python3.7/dist-packages/voxelmorph/torch/modelio.py", line 74, in load
    checkpoint = torch.load(path, map_location=torch.device(device))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'H'.
```

Have tried on 
- my laptop
OS: Win10
GPU: GTX 970m
CPU: Intel i7-6700HQ
`torch.__version__ = '1.6.0+cu101'`

- colab in [this link](https://colab.research.google.com/drive/1f9V30J5eyD-m1viJVSJKVkASeMXiBA8k?usp=sharing).

**Comment by rapotekhin** [comment]
same problem
