### ISSUE TITLE
Cannot run voxelmorph with synthmorph model

### ISSUE THREAD

**Issue by lchauvin** [voxelmorph/voxelmorph#618]
Hello,

I'm trying to run synthmorph, but I'm having this issue:

```
python ./scripts/tf/register.py --moved tmp.nii --moving /scratch/02/lchauvin/datasets/SynthMorph/img1_half_fov.nii --fixed /scratch/02/lchauvin/datasets/SynthMorph/img2_half_fov.nii --model models/synthmorph.deform.3.h5 

2024-09-20 19:09:45.209404: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-20 19:09:45.209460: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-20 19:09:45.211385: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-20 19:09:45.219011: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-20 19:09:45.927210: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-09-20 19:09:46.807881: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2024-09-20 19:09:46.807927: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:129] retrieving CUDA diagnostic information for host: imaging-gpu-05
2024-09-20 19:09:46.807934: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:136] hostname: imaging-gpu-05
2024-09-20 19:09:46.808014: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:159] libcuda reported version is: 535.183.1
2024-09-20 19:09:46.808038: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:163] kernel reported version is: 535.183.1
2024-09-20 19:09:46.808046: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:241] kernel version seems to match DSO: 535.183.1
Traceback (most recent call last):
  File "/scratch/02/lchauvin/workspace/projects/Voxelmorph/./scripts/tf/register.py", line 66, in <module>
    warp = vxm.networks.VxmDense.load(args.model, **config).register(moving, fixed)
  File "/home/lchauvin/.local/lib/python3.10/site-packages/neurite/tf/modelio.py", line 119, in load
    config = cls.load_config(path)
  File "/home/lchauvin/.local/lib/python3.10/site-packages/neurite/tf/modelio.py", line 131, in load_config
    s = f.attrs['model_config']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/lchauvin/.local/lib/python3.10/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 80, in h5py.h5a.open
KeyError: "Unable to synchronously open attribute (can't locate attribute: 'model_config')"
```

**Comment by mu40** [comment]
SynthMorph weight files do not include a `model_config` and are incompatible with the `VxmDense` network that the script `register.py` sets up. The easiest way to run SynthMorph is likely by using our [container image and wrapper script](https://hub.docker.com/r/freesurfer/synthmorph) with Docker, Podman, Apptainer, or Singularity.

If you prefer to run SynthMorph in your own environment, you can use the `mri_synthmorph` script, available under "Code and weights" at [synthmorph.io](https://synthmorph.io) along with the Python `requirements.txt` and the weights that you downloaded.

**Comment by lchauvin** [comment]
I thought SynthMorph was basically Voxelmorph with training on synthetic image. Why would the weight of Synthmorph not compatible with Voxelmorph ?

**Comment by mu40** [comment]
Since the initial IEEE TMI paper, we have continued to add to SynthMorph. The [current version](https://doi.org/10.1162/imag_a_00197) implements a HyperMorph-like network, which enables you to adjust the warp smoothness at test time using the model `HyperVxmJoint`.

![Test-time regularization](https://github.com/user-attachments/assets/035d213b-8661-4e4f-b4e0-c084ce4fbf1c)

This is why the weights you downloaded are not compatible with `VxmDense`. If you are looking for the original SynthMorph weights for `VxmDense`, these are still available in the SynthMorph section of our [README](https://github.com/voxelmorph/voxelmorph).
