### ISSUE TITLE
ValueError: Unknown loss function:loss

### ISSUE THREAD

**Issue by JCFu** [voxelmorph/voxelmorph#97]
Hi @adalca ,

I have trained my own model `05.h5` via `train.py`(cvpr version), but when it used in `python register.py --gpu 0 ../test_vol.nii.gz ../atlas_norm.nii.gz --out_img ../wrap.nii.gz --model_file ../models/05.h5 `and an error occurred.

```
(voxelmorph) jasonfu@jasonfu-Z370-HD3:~/voxelmorph/src$ python register.py --gpu 0 ../IXI001.nii.gz ../atlas_norm.nii.gz --out_img ../wrap.nii.gz --model_file ../models/05.h5 
Using TensorFlow backend.
2019-09-01 21:06:02.075134: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-01 21:06:02.144359: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-01 21:06:02.144634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.74GiB
2019-09-01 21:06:02.144647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-09-01 21:06:02.373578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-01 21:06:02.373604: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-09-01 21:06:02.373610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-09-01 21:06:02.373697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7477 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "register.py", line 104, in <module>
    register(**vars(args))
  File "register.py", line 67, in register
    net = keras.models.load_model(model_file, custom_objects=custom_objects)
  File "/home/jasonfu/anaconda3/envs/voxelmorph/lib/python3.6/site-packages/keras/models.py", line 301, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/home/jasonfu/anaconda3/envs/voxelmorph/lib/python3.6/site-packages/keras/engine/training.py", line 634, in compile
    loss_functions = [losses.get(l) for l in loss]
  File "/home/jasonfu/anaconda3/envs/voxelmorph/lib/python3.6/site-packages/keras/engine/training.py", line 634, in <listcomp>
    loss_functions = [losses.get(l) for l in loss]
  File "/home/jasonfu/anaconda3/envs/voxelmorph/lib/python3.6/site-packages/keras/losses.py", line 122, in get
    return deserialize(identifier)
  File "/home/jasonfu/anaconda3/envs/voxelmorph/lib/python3.6/site-packages/keras/losses.py", line 114, in deserialize
    printable_module_name='loss function')
  File "/home/jasonfu/anaconda3/envs/voxelmorph/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 164, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:loss
```
I

**Comment by John1231983** [comment]
Here you are. Check my answer
https://github.com/voxelmorph/voxelmorph/issues/68

**Comment by JCFu** [comment]
Dear @John1231983 ,
By using  you provided code, it appeared the same error.

**Comment by John1231983** [comment]
https://github.com/voxelmorph/voxelmorph/issues/68#issuecomment-526172320

**Comment by JCFu** [comment]
@John1231983  Fantastic!!! Thanks!

**Comment by JCFu** [comment]
@John1231983 
An other question. When training with ncc, the `loss` and `SpatialTransformer_loss` are negative. Is this normal?

**Comment by John1231983** [comment]
Yes. Search minus loss in issue you can find the answer why

**Comment by mamamadoge** [comment]
My loss and SpatialTransformer_loss are also minus, the others are positive, and is that normal?
And which one is means the model's better performance?
1.More negative like -10000
2.close to 0
Thank you!!!!!!

**Comment by adalca** [comment]
It is perfectly fine for the losses to have different signs. Please see #98

**Comment by mamamadoge** [comment]
Thank a lot for your reply.
And another question is that is it normal for spatial_transformer loss to change very slow?
It changes 0.1 after the data normalization to [0, 1]
Like from 0.97 to 0.9
